#!/usr/bin/env python3

"""
Script to save the occupancy grid map generated by SLAM.
Usage: ros2 run turtlebot3_mapping save_map.py [map_name]
"""

import rclpy
from rclpy.node import Node
from nav_msgs.msg import OccupancyGrid
from nav2_map_server import MapSaver
import sys
import os


class MapSaverNode(Node):
    def __init__(self, map_name='turtlebot3_map'):
        super().__init__('map_saver_node')
        self.map_name = map_name
        self.map_received = False
        
        # Subscribe to map topic
        self.map_sub = self.create_subscription(
            OccupancyGrid,
            '/map',
            self.map_callback,
            10
        )
        
        self.get_logger().info(f"Waiting for map on /map topic...")
        self.get_logger().info(f"Map will be saved as: {map_name}")
    
    def map_callback(self, msg):
        if not self.map_received:
            self.map_received = True
            self.get_logger().info(f"Map received! Resolution: {msg.info.resolution}m/pixel")
            self.get_logger().info(f"Map size: {msg.info.width}x{msg.info.height} pixels")
            self.get_logger().info(f"Map origin: ({msg.info.origin.position.x}, {msg.info.origin.position.y})")
            
            # Count known cells
            known_cells = sum(1 for cell in msg.data if cell != -1)
            total_cells = len(msg.data)
            self.get_logger().info(f"Known cells: {known_cells}/{total_cells} ({100*known_cells/total_cells:.1f}%)")


def main(args=None):
    rclpy.init(args=args)
    
    # Get map name from command line or use default
    map_name = 'turtlebot3_map'
    if len(sys.argv) > 1:
        map_name = sys.argv[1]
    
    map_saver = MapSaverNode(map_name)
    
    try:
        rclpy.spin_once(map_saver, timeout_sec=5.0)
        if map_saver.map_received:
            map_saver.get_logger().info("Map generated successfully!")
    except Exception as e:
        map_saver.get_logger().error(f"Error: {e}")
    finally:
        map_saver.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()

